services:
  capacitacionesv1.dev:
    build:
      context: ./docker/8.2
      dockerfile: Dockerfile
      args:
        WWWGROUP: "${WWWGROUP}"
        MYSQL_CLIENT: mariadb-client
    container_name: capacitacionesv1.dev
    image: sail-8.2/capacitacionesv1.dev
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "${APP_PORT:-80}:80"
      - "${VITE_PORT:-5173}:${VITE_PORT:-5173}"
      - '${REVERB_SERVER_PORT:-8080}:8080'
    environment:
      WWWUSER: "${WWWUSER}"
      LARAVEL_SAIL: 1
      PHP_CLI_SERVER_WORKERS: 5
      XDEBUG_MODE: "${SAIL_XDEBUG_MODE:-off}"
      XDEBUG_CONFIG: "${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}"
      IGNITION_LOCAL_SITES_PATH: "${PWD}"
    volumes:
      - ".:/var/www/html"
networks:
  default:
    external: true
    name: proxygratis
