INSERT INTO patologias (nombre, descripcion) VALUES
	('Aritmia', NULL),
	('Artrosis', NULL),
	('Asma Leve', NULL),
	('Asma Moderada', NULL),
	('Càncer de Mama', NULL),
	('Càncer de Ovario', NULL),
	('Càncer de Prostota', NULL),
	('Cardiopatìa Izquemica', NULL),
	('Diabetes', NULL),
	('Diabetes Mellitus tipo II', 'E14'),
	('Gastritis', 'K29'),
	('Gota', 'M10.3'),
	('Hiperparatiroidismo', 'E21.3'),
	('Hipertenciòn Arterial', 'I15.0'),
	('Hipertiroidismo', 'E05.0'),
	('Lupus', 'M32.9'),
	('Obesidad', 'E66.9'),
	('Obesidad Mórbida', 'E66.01');