INSERT INTO unidad_organicas (nombre) VALUES
    ('Ambulancia'),
    ('Lavandería'),
    ('Mantenimiento'),
    ('Saneamiento Ambiental y Zoonosis'),
    ('Servicio de Admisión'),
    ('Servicio de Capacitación'),
    ('Servicio de Ecografía'),
    ('Servicio de Epidemiología'),
    ('Servicio de Medicina de Familia'),
    ('Servicio de Medicina General'),
    ('Servicio de Nutrición'),
    ('Servicio de Rayos X'),
    ('Servicio de Terapia Física y Rehabilitación'),
    ('Servicio Dental'),
    ('Servicio Emergencia'),
    ('Servicio Enfermería'),
    ('Servicio Estadística'),
    ('Servicio Farmacia'),
    ('Servicio Laboratorio'),
    ('Servicio Logística'),
    ('Servicio Obstetricia'),
    ('Servicio Oficina de Seguros'),
    ('Servicio Oftalmología'),
    ('Servicio PCT'),
    ('Servicio Pediatría'),
    ('Servicio Personal'),
    ('Servicio Psicología'),
    ('Servicio Secretaría'),
    ('Servicio Social'),
    ('Servicio Caja General'),
    ('Vigilancia');
